// <auto-generated />
using System;
using FoodBev.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodBev.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125234807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CV_File_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateAvailability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentFormDocumentRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterviewVenue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisteredBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.HasIndex("CandidateID");

                    b.HasIndex("JobID", "CandidateID")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.CandidateEntity", b =>
                {
                    b.Property<int>("CandidateID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptsPOPI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestQualification")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ID_Document_Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("OFO_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualificationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateID");

                    b.HasIndex("IDNumber")
                        .IsUnique();

                    b.ToTable("CandidateDetails");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.EmployerEntity", b =>
                {
                    b.Property<int>("EmployerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LevyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SDFContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SDFEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SDFName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployerID");

                    b.HasIndex("LevyNumber")
                        .IsUnique();

                    b.ToTable("EmployerDetails");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.JobPosting", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployerID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBursary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OFO_Code_Required")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobID");

                    b.HasIndex("EmployerID");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.OfoCode", b =>
                {
                    b.Property<int>("OfoCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OfoCodeID");

                    b.ToTable("OfoCodes");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.SkillsProgrammeForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminRegistrationNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployerSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingProviderSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FormID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.ToTable("SkillsProgrammeForms");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.ApplicationEntity", b =>
                {
                    b.HasOne("FoodBev.Core.Domain.Entities.CandidateEntity", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodBev.Core.Domain.Entities.JobPosting", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("FoodBev.Core.Domain.Entities.EmployerEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.SkillsProgrammeForm", b =>
                {
                    b.HasOne("FoodBev.Core.Domain.Entities.ApplicationEntity", "Application")
                        .WithOne("SkillsProgrammeForm")
                        .HasForeignKey("FoodBev.Core.Domain.Entities.SkillsProgrammeForm", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("SkillsProgrammeForm");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.CandidateEntity", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("FoodBev.Core.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
